apiVersion: v1
kind: Namespace
metadata:
  name: librespeed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
  namespace: librespeed
  labels:
    app: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librespeed
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
        - name: librespeed
          image: linuxserver/librespeed:latest
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Europe/Berlin
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: librespeed
  namespace: librespeed
spec:
  selector:
    app: librespeed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librespeed
  namespace: librespeed
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: librespeed
                port:
                  number: 80
