apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kube-prometheus-stack
  namespace: fleet-local
spec:
  repo: https://github.com/jonded94/nixos-config.git
  branch: main
  paths:
    - charts/kube-prometheus-stack
  pollingInterval: 1m
